[package]
name = "cluster"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
assert_cmd = "2.0.11"
tempfile = "3.2.0"